spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      default-filters:
        - PrefixPath=/api/v1
      routes:
        - id: shopping_cart_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
        - id: shopping_store_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
        - id: delivery_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: payment_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: warehouse_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**

server:
  port: 8080